# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"logger": "0_Short-Text-Analyzer_core.ipynb",
         "shortTextAnalyzer": "0_Short-Text-Analyzer_core.ipynb",
         "dataDetectLang": "0_Short-Text-Analyzer_core.ipynb",
         "dataTranslateToEng": "0_Short-Text-Analyzer_core.ipynb",
         "embeddingComments": "0_Short-Text-Analyzer_core.ipynb",
         "analyzePolarity": "0_Short-Text-Analyzer_core.ipynb",
         "analyzeSubjectivity": "0_Short-Text-Analyzer_core.ipynb",
         "clusterByHBDSCAN": "0_Short-Text-Analyzer_core.ipynb",
         "clusterByKMeans": "0_Short-Text-Analyzer_core.ipynb"}

modules = ["core.py"]

doc_url = "https://thisisphume.github.io/shorttextanalyzer/"

git_url = "https://github.com/thisisphume/shorttextanalyzer/tree/master/"

def custom_doc_links(name): return None
